#[derive(Hash, Eq, PartialEq, Clone, Copy, Debug)]
pub enum GPUMemoryOperation {
    Addition,
    Subtract,
    Multiply,
    Divide,
    Maximum,
    Minimum,
    ReLU,
    Sigmoid,
    Softmax,
    Conv2D,
    MatMul,
    MatMul1D2D,
    MatMul2D1D,
    MatMul2D2D,
    MatMul2D3D,
    MatMul3D2D,
    MatMul3D3D,
    MatMul3D1D,
    MatMul1D3D,
    InitXavier,
    InitHe,
    InitUniform,
    InitNormal,
    InitConstant,
}
