#version 450

layout(local_size_x = 256) in;

layout(std430, binding = 0) buffer InBuffer { float a[]; };
layout(std430, binding = 2) buffer OutBuffer { float b[]; };

layout(push_constant) uniform PushConstants {
    float alpha;
} constants;

void main() {
    uint idx = gl_GlobalInvocationID.x;
    if (idx < a.length()) {
        float x = a[idx];
        b[idx] = x > 0.0 ? x : constants.alpha * x;
    }
}
